zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    product-service:
      path: /product/**
      serviceId: product-service
      stripPrefix: false
      url: product-service

    order-service:
      path: /order/**
      serviceId: order-service
      stripPrefix: false
      url: order-service

    swagger-service:
      path: /api/**
      serviceId: swagger-server
      stripPrefix: true
      url: swagger-server

    authorization-server:
      path: /user/**
      serviceId: authorization-server
      stripPrefix: false
      url : authorization-server

    authorization-server-oauth:
      path: /oauth/**
      serviceId: authorization-server
      stripPrefix: false
      url: authorization-server


security:
  oauth2:
    client:
      client-id: volt-android
      client-secret: volt
    authorization:
      token-key-access: isAuthenticated()
    resource:
      #      token-info-uri: http://localhost:9000/oauth/check_token
      jwt:
        key-uri: http://localhost:9000/oauth/token_key
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost2:8762/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5