server:
  port: 8080

zuul:
  routes:
    product-service:
      path: /product/**
      serviceId: product-service
      stripPrefix: false
      url: product-service

    swagger-service:
      path: /api/**
      serviceId: swagger-server
      stripPrefix: true
      url: swagger-server
  sensitiveHeaders: Cookie,Set-Cookie



security:
  oauth2:
    client:
      client-id: volt-android
      client-secret: volt
    authorization:
      token-key-access: isAuthenticated()
    resource:
      #      token-info-uri: http://localhost:9000/oauth/check_token
      jwt:
        key-uri: http://localhost:9000/oauth/token_key
#spring.cloud.gateway.routes:
#- id: product-service
#  uri: lb://product-service
#  predicates:
#    - Path=/product-service/**
#
#- id: spring-admin-api
#  uri: http://localhost:8081
#  predicates:
#    - Path=/**
#  filter:
#    - SetPath=/**
#
#
#
#- id: eureka-api
#  uri: lb://eureka-server
#  predicates:
#    - Path=/eureka/api/{segment}
#  filters:
#    - SetPath=/eureka/{segment}
#
#- id: eureka-web-start
#  uri: lb://eureka-server
#  predicates:
#    - Path=/eureka/web
#  filters:
#    - SetPath=/
#
#- id: eureka-web-other
#  uri: lb://eureka-server
#  predicates:
#    - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost2:8762/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5