server:
  port: 8088
spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DEU-Volt/spring-cloud-config-repository
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost2:8762/eureka/
#      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: false
      fetch-registry: false
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
