server:
  port: 8088
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/, http://localhost2:8762/eureka/
#      register-with-eureka: false
#      fetch-registry: false
#    initialInstanceInfoReplicationIntervalSeconds: 5
#    registryFetchIntervalSeconds: 5
#  instance:
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 5
